"use client"

import { useState } from "react"
import { motion, AnimatePresence } from "framer-motion"
import { X, FileText, Download, Loader2 } from "lucide-react"
import type { MatchedQuestion, PredictionResult } from "@/lib/api"
import type { Chapter } from "@/lib/storage"

interface ExportModalProps {
  mode: string
  chapters: Chapter[]
  analysis: {
    matchedQuestions?: MatchedQuestion[]
    chapterCounts?: Record<number, number>
    predictions?: PredictionResult | null
  } | null
  subjectName: string
  onClose: () => void
}

async function generatePDF(title: string, sections: { heading: string; body: string }[]): Promise<Blob> {
  const { jsPDF } = await import("jspdf")
  const doc = new jsPDF({ unit: "mm", format: "a4" })

  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 20
  const maxWidth = pageWidth - margin * 2
  let y = 25

  const checkPage = (needed: number) => {
    const pageHeight = doc.internal.pageSize.getHeight()
    if (y + needed > pageHeight - 20) {
      doc.addPage()
      y = 20
    }
  }

  // Title
  doc.setFont("helvetica", "bold")
  doc.setFontSize(18)
  doc.text(title, margin, y)
  y += 10

  doc.setFontSize(8)
  doc.setFont("helvetica", "normal")
  doc.setTextColor(120)
  doc.text(`Generated by OracleSort — ${new Date().toLocaleDateString()}`, margin, y)
  y += 10
  doc.setTextColor(0)

  for (const section of sections) {
    checkPage(20)

    doc.setFont("helvetica", "bold")
    doc.setFontSize(13)
    const headingLines = doc.splitTextToSize(section.heading, maxWidth)
    doc.text(headingLines, margin, y)
    y += headingLines.length * 6 + 3

    doc.setFont("helvetica", "normal")
    doc.setFontSize(10)
    const bodyLines = doc.splitTextToSize(section.body, maxWidth)

    for (const line of bodyLines) {
      checkPage(7)
      doc.text(line, margin, y)
      y += 5
    }

    y += 6
  }

  return doc.output("blob")
}

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

function buildChapterSections(
  chapters: Chapter[],
  analysis: ExportModalProps["analysis"]
): { heading: string; body: string }[] {
  const questions = analysis?.matchedQuestions || []
  const sections: { heading: string; body: string }[] = []

  for (const chapter of chapters) {
    const chapterQuestions = questions.filter((q) => q.chapterNumber === chapter.number)
    if (chapterQuestions.length === 0) continue

    let body = ""
    chapterQuestions.forEach((q, i) => {
      body += `Q${i + 1} [${q.type.toUpperCase()}] ${q.text}\n`
      if (q.options?.length) {
        q.options.forEach((opt, j) => {
          body += `  ${String.fromCharCode(65 + j)}. ${opt}\n`
        })
      }
      if (q.imageDescription) body += `  [Image: ${q.imageDescription}]\n`
      if (q.marks) body += `  (${q.marks} marks)\n`
      body += `  Source: ${q.sourceDocument}\n\n`
    })

    sections.push({
      heading: `Chapter ${chapter.number}: ${chapter.title} (${chapterQuestions.length} questions)`,
      body: body.trimEnd(),
    })
  }

  return sections
}

function buildPredictionSection(predictions: PredictionResult | null | undefined): { heading: string; body: string } | null {
  if (!predictions?.predictions?.length) return null

  let body = ""
  for (const p of predictions.predictions) {
    const label = p.probability > 0.7 ? "HIGH" : p.probability >= 0.4 ? "MEDIUM" : "LOW"
    body += `Ch ${p.chapterNumber}: ${p.chapterTitle} — ${Math.round(p.probability * 100)}% (${label})\n  ${p.reason}\n\n`
  }
  if (predictions.summary) {
    body += `Summary: ${predictions.summary}\n`
  }

  return { heading: "Exam Predictions", body: body.trimEnd() }
}

export function ExportModal({ mode, chapters, analysis, subjectName, onClose }: ExportModalProps) {
  const [isExporting, setIsExporting] = useState(false)
  const isSeparate = mode === "separate"

  const handleExport = async () => {
    setIsExporting(true)

    try {
      const chapterSections = buildChapterSections(chapters, analysis)
      const predictionSection = buildPredictionSection(analysis?.predictions)

      if (isSeparate) {
        // One PDF per chapter
        for (const section of chapterSections) {
          const sections = predictionSection ? [section, predictionSection] : [section]
          const blob = await generatePDF(
            `${subjectName} — ${section.heading}`,
            sections
          )
          const safeName = section.heading.replace(/[^a-zA-Z0-9]/g, "_").slice(0, 40)
          downloadBlob(blob, `${subjectName}_${safeName}.pdf`)
        }
      } else {
        // Single combined PDF
        const allSections = [...chapterSections]
        if (predictionSection) allSections.push(predictionSection)
        const blob = await generatePDF(
          `${subjectName} — Complete Analysis`,
          allSections
        )
        downloadBlob(blob, `${subjectName}_Complete_Analysis.pdf`)
      }

      onClose()
    } catch {
      // Export failed silently
    } finally {
      setIsExporting(false)
    }
  }

  const chapterCount = chapters.filter(
    (c) => (analysis?.matchedQuestions || []).some((q) => q.chapterNumber === c.number)
  ).length

  return (
    <AnimatePresence>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        className="fixed inset-0 z-50 flex items-center justify-center backdrop-blur-sm"
        onClick={onClose}
      >
        <div className="absolute inset-0 bg-background/70" />
        <motion.div
          initial={{ scale: 0.95, opacity: 0 }}
          animate={{ scale: 1, opacity: 1 }}
          exit={{ scale: 0.95, opacity: 0 }}
          className="relative w-full max-w-md rounded-2xl border border-border bg-card p-6 shadow-xl"
          onClick={(e) => e.stopPropagation()}
        >
          <div className="mb-4 flex items-center justify-between">
            <h3 className="font-serif text-lg font-medium text-foreground">
              {isSeparate ? "Export Separate PDFs" : "Export Combined PDF"}
            </h3>
            <button
              onClick={onClose}
              className="flex h-7 w-7 items-center justify-center rounded-full text-muted-foreground hover:bg-muted"
            >
              <X className="h-4 w-4" />
            </button>
          </div>

          <div className="mb-6 space-y-3">
            <div className="flex items-center gap-3 rounded-lg border border-border bg-background p-3">
              <FileText className="h-5 w-5 text-muted-foreground" strokeWidth={1.5} />
              <div>
                <p className="text-sm font-medium text-foreground">
                  {isSeparate ? `${chapterCount} chapter PDFs` : "1 combined PDF"}
                </p>
                <p className="text-xs text-muted-foreground">
                  {isSeparate
                    ? "Each chapter as a separate file with its questions"
                    : "All chapters and predictions in one document"}
                </p>
              </div>
            </div>

            <div className="rounded-lg bg-muted/50 p-3">
              <p className="text-xs text-muted-foreground">
                Includes: questions per chapter, question types, source documents
                {analysis?.predictions ? ", and exam predictions" : ""}
              </p>
            </div>
          </div>

          <div className="flex justify-end gap-3">
            <button
              onClick={onClose}
              className="rounded-lg px-4 py-2 text-xs font-medium text-muted-foreground hover:bg-muted"
            >
              Cancel
            </button>
            <button
              onClick={handleExport}
              disabled={isExporting}
              className="flex items-center gap-2 rounded-lg bg-primary px-4 py-2 text-xs font-medium text-primary-foreground hover:bg-primary/90 disabled:opacity-50"
            >
              {isExporting ? (
                <Loader2 className="h-3.5 w-3.5 animate-spin" />
              ) : (
                <Download className="h-3.5 w-3.5" />
              )}
              {isExporting ? "Exporting..." : "Download"}
            </button>
          </div>
        </motion.div>
      </motion.div>
    </AnimatePresence>
  )
}
