"use client"

import { useState, useCallback } from "react"
import { motion, AnimatePresence } from "framer-motion"
import { X, FileText, Download } from "lucide-react"

export function ExportModal({ mode, chapters, analysis, subjectName, onClose }) {
  const [selected, setSelected] = useState(chapters.map((c) => c.chapterNumber))
  const [sortBy, setSortBy] = useState("chapter")
  const [isGenerating, setIsGenerating] = useState(false)

  const toggleAll = useCallback(() => {
    setSelected(chapters.length === selected.length ? [] : chapters.map((c) => c.chapterNumber))
  }, [chapters, selected])

  const toggleChapter = useCallback(
    (num) => {
      setSelected((prev) =>
        prev.includes(num) ? prev.filter((n) => n !== num) : [...prev, num]
      )
    },
    []
  )

  const handleGenerate = useCallback(async () => {
    if (!selected.length || !analysis?.matchedQuestions) return
    setIsGenerating(true)

    try {
      const { jsPDF } = await import("jspdf").then((mod) => mod)

      const questionsByChapter = {}
      for (const q of analysis.matchedQuestions) {
        if (selected.includes(q.chapterNumber)) {
          const key = q.chapterNumber
          if (!questionsByChapter[key]) questionsByChapter[key] = []
          questionsByChapter[key].push(q)
        }
      }

      if (mode === "separate") {
        for (const chNum of selected) {
          const chapter = chapters.find((c) => c.chapterNumber === chNum)
          const questions = questionsByChapter[chNum] || []
          if (!questions.length) continue

          const doc = new jsPDF()
          doc.setFontSize(18)
          doc.text(`Chapter ${chNum}: ${chapter?.chapterName || ""}`, 20, 30)
          doc.setFontSize(10)
          doc.text(`${questions.length} question(s)`, 20, 40)
          doc.setFontSize(11)

          let y = 55
          questions.forEach((q, i) => {
            if (y > 270) {
              doc.addPage()
              y = 20
            }
            doc.text(`${i + 1}. [${q.type || "Q"}] ${q.question}`, 20, y, { maxWidth: 170 })
            y += 12
          })

          doc.save(`Chapter_${chNum}_${(chapter?.chapterName || "Questions").replace(/\s+/g, "_")}.pdf`)
        }
      } else {
        const doc = new jsPDF()
        doc.setFontSize(20)
        doc.text(`${subjectName} - Combined Questions`, 20, 30)
        doc.setFontSize(10)
        doc.text(`Generated by OracleSort`, 20, 38)

        const sortedSelected = [...selected].sort((a, b) => {
          if (sortBy === "frequency") {
            const freqA = analysis.chapterFrequency?.[a] || 0
            const freqB = analysis.chapterFrequency?.[b] || 0
            return freqB - freqA
          }
          return a - b
        })

        let y = 50
        sortedSelected.forEach((chNum) => {
          const chapter = chapters.find((c) => c.chapterNumber === chNum)
          const questions = questionsByChapter[chNum] || []
          if (!questions.length) return

          if (y > 260) {
            doc.addPage()
            y = 20
          }

          doc.setFontSize(14)
          doc.text(`Chapter ${chNum}: ${chapter?.chapterName || ""}`, 20, y)
          y += 8
          doc.setFontSize(9)
          doc.text(`${questions.length} question(s)`, 20, y)
          y += 8
          doc.setFontSize(11)

          questions.forEach((q, i) => {
            if (y > 270) {
              doc.addPage()
              y = 20
            }
            doc.text(`${i + 1}. [${q.type || "Q"}] ${q.question}`, 20, y, { maxWidth: 170 })
            y += 12
          })

          y += 8
        })

        doc.save(`${subjectName.replace(/\s+/g, "_")}_Combined_Questions.pdf`)
      }
    } catch (err) {
      console.error("Export failed:", err)
    } finally {
      setIsGenerating(false)
      onClose()
    }
  }, [selected, analysis, chapters, mode, sortBy, subjectName, onClose])

  return (
    <AnimatePresence>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        className="fixed inset-0 z-50 flex items-center justify-center backdrop-blur-sm"
        onClick={onClose}
      >
        <div className="absolute inset-0 bg-background/70" />

        <motion.div
          initial={{ scale: 0.95, opacity: 0 }}
          animate={{ scale: 1, opacity: 1 }}
          exit={{ scale: 0.95, opacity: 0 }}
          className="relative w-full max-w-lg rounded-2xl border border-border bg-card p-6 shadow-xl"
          onClick={(e) => e.stopPropagation()}
        >
          <div className="mb-4 flex items-center justify-between">
            <h3 className="font-serif text-lg font-medium text-foreground">
              {mode === "separate" ? "Export Separate PDFs" : "Export Combined PDF"}
            </h3>
            <button
              onClick={onClose}
              className="flex h-7 w-7 items-center justify-center rounded-full text-muted-foreground hover:bg-muted"
            >
              <X className="h-4 w-4" />
            </button>
          </div>

          {/* Sort option for combined mode */}
          {mode === "combined" && (
            <div className="mb-4 flex gap-2">
              <button
                onClick={() => setSortBy("chapter")}
                className={`rounded-lg px-3 py-1.5 text-xs font-medium transition-colors ${
                  sortBy === "chapter"
                    ? "bg-primary text-primary-foreground"
                    : "bg-muted text-muted-foreground hover:bg-accent"
                }`}
              >
                Order by chapter number
              </button>
              <button
                onClick={() => setSortBy("frequency")}
                className={`rounded-lg px-3 py-1.5 text-xs font-medium transition-colors ${
                  sortBy === "frequency"
                    ? "bg-primary text-primary-foreground"
                    : "bg-muted text-muted-foreground hover:bg-accent"
                }`}
              >
                Order by frequency
              </button>
            </div>
          )}

          {/* Select all / deselect */}
          <div className="mb-3 flex gap-2">
            <button
              onClick={toggleAll}
              className="rounded-lg bg-muted px-3 py-1.5 text-xs font-medium text-muted-foreground hover:bg-accent"
            >
              {selected.length === chapters.length ? "Deselect All" : "Select All"}
            </button>
            <span className="self-center text-xs text-muted-foreground">
              {selected.length} of {chapters.length} selected
            </span>
          </div>

          {/* Chapter checkboxes */}
          <div className="max-h-60 space-y-2 overflow-y-auto">
            {chapters.map((ch) => (
              <label
                key={ch.chapterNumber}
                className={`flex cursor-pointer items-center gap-3 rounded-lg border px-3 py-2 transition-colors ${
                  selected.includes(ch.chapterNumber)
                    ? "border-primary/30 bg-accent/50"
                    : "border-border hover:bg-muted/30"
                }`}
              >
                <input
                  type="checkbox"
                  checked={selected.includes(ch.chapterNumber)}
                  onChange={() => toggleChapter(ch.chapterNumber)}
                  className="accent-primary"
                />
                <span className="text-sm text-foreground">
                  Ch {ch.chapterNumber}: {ch.chapterName}
                </span>
              </label>
            ))}
          </div>

          <div className="mt-6 flex justify-end gap-3">
            <button
              onClick={onClose}
              className="rounded-lg px-4 py-2 text-xs font-medium text-muted-foreground hover:bg-muted"
            >
              Cancel
            </button>
            <button
              onClick={handleGenerate}
              disabled={!selected.length || isGenerating}
              className="flex items-center gap-2 rounded-lg bg-primary px-4 py-2 text-xs font-medium text-primary-foreground hover:bg-primary/90 disabled:cursor-not-allowed disabled:opacity-50"
            >
              <Download className="h-3.5 w-3.5" />
              {isGenerating ? "Generating..." : "Generate"}
            </button>
          </div>
        </motion.div>
      </motion.div>
    </AnimatePresence>
  )
}
